### ISSUE TITLE
Void and oneway methods fail to compile

### ISSUE THREAD

**Issue by jorgeortiz85** [foursquare/spindle#38]
Methods that return "void" or are marked as "oneway" will fail to compile.

For example, add the following file as `src/test/thrift/com/foursquare/spindle/codegen/service.thrift` and run `test`:

```
// Copyright 2014 Foursquare Labs Inc. All Rights Reserved.

namespace java com.foursquare.spindle.test.gen

service AService {
  void aMethod()
  oneway i32 bMethod()
  onway void cMethod()
  i32 dMethod()
}
```

**Comment by tdyas** [comment]
Fix with test at: https://github.com/foursquare/spindle/pull/44
