### ISSUE TITLE
Test suite fails for 2.10

### ISSUE THREAD

**Issue by aposwolsky** [foursquare/spindle#5]
Currently ./sbt +test fails since it cannot find a Scala 2.10 version of com.twitter#finagle-thrift.  I can complete the test suite by removing it from Keys.crossScalaVersions.

**Comment by blackmad** [comment]
err, can you leave it and I'll fix it? I'm getting close to this being the
release branch and I'd like to maintain 2.10 compatibility

**Comment by aposwolsky** [comment]
yep.. sgtm.  thanks!

**Comment by jorgeortiz85** [comment]
The fix is in v1.4.x branch (that I haven't pushed to github yet). I'll merge it into master as well.

**Comment by jorgeortiz85** [comment]
Should be fixed in master.
